In [ ]:
!pip install -q kaggle

In [ ]:
!mkdir ~/.kaggle

In [ ]:
!cp kaggle.json ~/.kaggle

In [ ]:
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle datasets list

Warning: Looks like you're using an outdated API Version, please consider updating (server 1.6.11 / client 1.5.16)
ref                                                           title                                            size  lastUpdated          downloadCount  voteCount  usabilityRating
------------------------------------------------------------  ----------------------------------------------  -----  -------------------  -------------  ---------  ---------------
sudarshan24byte/online-food-dataset                           Online Food Dataset                               3KB  2024-03-02 18:50:30          26584        522  0.9411765
nbroad/gemma-rewrite-nbroad                                   gemma-rewrite-nbroad                              8MB  2024-03-03 04:52:39           1663        104  1.0
lovishbansal123/adult-census-income                           Adult Census Income                             450KB  2024-04-12 08:18:30            489         23  1.0
sukhmandeepsinghbrar/most-subscribed-youtube-channel          Most Subscribed YouTube Channel                   1KB  2024-04-10 20:33:05           1102         34  1.0
sanyamgoyal401/customer-purchases-behaviour-dataset           Customer Purchases Behaviour Dataset              1MB  2024-04-06 18:42:01           1672         41  1.0
startalks/pii-models                                          pii-models                                        1GB  2024-03-21 21:23:40            118         19  1.0
fatemehmehrparvar/obesity-levels                              Obesity Levels                                   58KB  2024-04-07 16:28:30           1866         46  0.88235295
sahirmaharajj/employee-salaries-analysis                      Employee Salaries Analysis                      101KB  2024-03-31 16:32:47           1590         48  1.0
bhavikjikadara/student-study-performance                      Student Study Performance                         9KB  2024-03-07 06:14:09          12884        168  1.0
soumyajitjalua/crop-datasets-for-all-indian-states-2010-2017  Crop Datasets for All Indian States: 2010-2017  305KB  2024-04-09 15:16:46            484         24  1.0
sukhmandeepsinghbrar/housing-price-dataset                    Housing Price Dataset                           780KB  2024-04-04 19:45:43           1830         35  1.0
divu2001/restaurant-order-data                                Restaurant Order Data                           426KB  2024-04-10 08:33:29            669         24  1.0
willianoliveiragibin/worlds-wildlife                          worldâ€™s wildlife?                                92KB  2024-04-12 19:44:08            426         21  1.0
sahirmaharajj/air-pollution-dataset                           Air Pollution Dataset                           213KB  2024-04-07 13:14:48           1242         39  1.0
joshuanaude/effects-of-alcohol-on-student-performance         Effects of Alcohol on Student Performance.        9KB  2024-03-25 12:08:03           1627         34  1.0
zubairmustafa/shopping-mall-customer-segmentation-data        Shopping Mall Customer Segmentation Data        426KB  2024-03-29 20:36:22            898         21  0.9411765
mohdshahnawazaadil/credit-card-dataset                        Credit Card Dataset                              66MB  2024-04-02 00:04:05           1107         27  1.0
sahilnbajaj/loans-data                                        Loans Data                                      213KB  2024-04-07 15:08:37           1110         29  1.0
rushikeshdane20/global-trends-in-atmospheric-carbon-dioxide   Global Trends in Atmospheric CO2 Emission        20KB  2024-04-13 03:45:31            601         22  0.8235294
sahirmaharajj/electric-vehicle-population-size-2024           Electric Vehicle Population by Country (2024)   275KB  2024-03-30 19:16:06           2329         62  1.0

In [ ]:
!kaggle datasets download 'sudarshan24byte/online-food-dataset'

Downloading online-food-dataset.zip to /content
  0% 0.00/3.37k [00:00<?, ?B/s]
100% 3.37k/3.37k [00:00<00:00, 7.32MB/s]

In [ ]:
!unzip online-food-dataset.zip

Archive:  online-food-dataset.zip
  inflating: onlinefoods.csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
path = "onlinefoods.csv"
df = pd.read_csv(path)

In [ ]:
df.head()

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
0,20,Female,Single,Student,No Income,Post Graduate,4,12.9766,77.5993,560001,Yes,Positive,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,12.9770,77.5773,560009,Yes,Positive,Yes
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,12.9551,77.6593,560017,Yes,Negative,Yes
3,22,Female,Single,Student,No Income,Graduate,6,12.9473,77.5616,560019,Yes,Positive,Yes
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,12.9850,77.5533,560010,Yes,Positive,Yes

In [ ]:
!kaggle datasets download -d 'shreyanshkhandelwal/goal-dataset-top-5-european-leagues'

Downloading goal-dataset-top-5-european-leagues.zip to /content
100% 174k/174k [00:00<00:00, 692kB/s]
100% 174k/174k [00:00<00:00, 691kB/s]

In [ ]:
!unzip goal-dataset-top-5-european-leagues.zip

Archive:  goal-dataset-top-5-european-leagues.zip
  inflating: Bundesliga-goalScorer(20-21).csv
  inflating: LaLiga-goalScorer(20-21).csv
  inflating: Ligue_1-goalScorer(20-21).csv
  inflating: Serie_A-goalScorer(20-21).csv
  inflating: epl-goalScorer(20-21).csv

In [ ]:
path = "epl-goalScorer(20-21).csv"
df = pd.read_csv(path)

In [ ]:
df.head()

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,0,647,Harry Kane,35,3097,23,22.174859,14,7.577094,138,49,1,0,F,Tottenham,19,19.130183,24.995648,4.451257
1,1,1250,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,55,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236
2,2,1228,Bruno Fernandes,37,3117,18,16.019454,12,11.474996,121,95,6,0,M S,Manchester United,9,8.407840,26.911412,11.932285
3,3,453,Son Heung-Min,37,3139,17,11.023287,10,9.512992,68,75,0,0,F M S,Tottenham,16,10.262118,20.671916,6.608751
4,4,822,Patrick Bamford,38,3085,17,18.401863,7,3.782247,107,30,3,0,F S,Leeds,15,16.879525,23.394953,4.131796

In [ ]:
print(df.dtypes)

Unnamed: 0        int64
id                int64
player_name      object
games             int64
time              int64
goals             int64
xG              float64
assists           int64
xA              float64
shots             int64
key_passes        int64
yellow_cards      int64
red_cards         int64
position         object
team_title       object
npg               int64
npxG            float64
xGChain         float64
xGBuildup       float64
dtype: object